package com.roy.mapper;

import com.roy.model.Calculate;
import com.roy.model.CalculateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CalculateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calculate
     *
     * @mbg.generated
     */
    long countByExample(CalculateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calculate
     *
     * @mbg.generated
     */
    int deleteByExample(CalculateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calculate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calculate
     *
     * @mbg.generated
     */
    int insert(Calculate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calculate
     *
     * @mbg.generated
     */
    int insertSelective(Calculate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calculate
     *
     * @mbg.generated
     */
    List<Calculate> selectByExample(CalculateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calculate
     *
     * @mbg.generated
     */
    Calculate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calculate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Calculate record, @Param("example") CalculateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calculate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Calculate record, @Param("example") CalculateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calculate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Calculate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_calculate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Calculate record);
}