package com.roy.mapper;

import com.roy.model.Judge;
import com.roy.model.JudgeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface JudgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_judeg
     *
     * @mbg.generated
     */
    long countByExample(JudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_judeg
     *
     * @mbg.generated
     */
    int deleteByExample(JudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_judeg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_judeg
     *
     * @mbg.generated
     */
    int insert(Judge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_judeg
     *
     * @mbg.generated
     */
    int insertSelective(Judge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_judeg
     *
     * @mbg.generated
     */
    List<Judge> selectByExample(JudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_judeg
     *
     * @mbg.generated
     */
    Judge selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_judeg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Judge record, @Param("example") JudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_judeg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Judge record, @Param("example") JudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_judeg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Judge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_judeg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Judge record);
}