package com.roy.mapper;

import com.roy.model.MultiSelect;
import com.roy.model.MultiSelectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MultiSelectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_multi_select
     *
     * @mbg.generated
     */
    long countByExample(MultiSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_multi_select
     *
     * @mbg.generated
     */
    int deleteByExample(MultiSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_multi_select
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_multi_select
     *
     * @mbg.generated
     */
    int insert(MultiSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_multi_select
     *
     * @mbg.generated
     */
    int insertSelective(MultiSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_multi_select
     *
     * @mbg.generated
     */
    List<MultiSelect> selectByExample(MultiSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_multi_select
     *
     * @mbg.generated
     */
    MultiSelect selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_multi_select
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MultiSelect record, @Param("example") MultiSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_multi_select
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MultiSelect record, @Param("example") MultiSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_multi_select
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MultiSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_multi_select
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MultiSelect record);
}