package com.roy.mapper;

import com.roy.model.PaperStandard;
import com.roy.model.PaperStandardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface PaperStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_standard
     *
     * @mbg.generated
     */
    long countByExample(PaperStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_standard
     *
     * @mbg.generated
     */
    int deleteByExample(PaperStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_standard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_standard
     *
     * @mbg.generated
     */
    int insert(PaperStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_standard
     *
     * @mbg.generated
     */
    int insertSelective(PaperStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_standard
     *
     * @mbg.generated
     */
    List<PaperStandard> selectByExample(PaperStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_standard
     *
     * @mbg.generated
     */
    PaperStandard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_standard
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PaperStandard record, @Param("example") PaperStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_standard
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PaperStandard record, @Param("example") PaperStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaperStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaperStandard record);
}