package com.roy.mapper;

import com.roy.model.Paper;
import com.roy.model.PaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface PaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    long countByExample(PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    int deleteByExample(PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    int insert(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    int insertSelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    List<Paper> selectByExample(PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    Paper selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Paper record, @Param("example") PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Paper record, @Param("example") PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Paper record);
}