package com.roy.mapper;

import com.roy.model.StuScore;
import com.roy.model.StuScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface StuScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_score
     *
     * @mbg.generated
     */
    long countByExample(StuScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_score
     *
     * @mbg.generated
     */
    int deleteByExample(StuScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_score
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_score
     *
     * @mbg.generated
     */
    int insert(StuScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_score
     *
     * @mbg.generated
     */
    int insertSelective(StuScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_score
     *
     * @mbg.generated
     */
    List<StuScore> selectByExample(StuScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_score
     *
     * @mbg.generated
     */
    StuScore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_score
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StuScore record, @Param("example") StuScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_score
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StuScore record, @Param("example") StuScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StuScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StuScore record);
}