package com.roy.mapper;

import com.roy.model.TeacCourse;
import com.roy.model.TeacCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TeacCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teac_course
     *
     * @mbg.generated
     */
    long countByExample(TeacCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teac_course
     *
     * @mbg.generated
     */
    int deleteByExample(TeacCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teac_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teac_course
     *
     * @mbg.generated
     */
    int insert(TeacCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teac_course
     *
     * @mbg.generated
     */
    int insertSelective(TeacCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teac_course
     *
     * @mbg.generated
     */
    List<TeacCourse> selectByExample(TeacCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teac_course
     *
     * @mbg.generated
     */
    TeacCourse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teac_course
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TeacCourse record, @Param("example") TeacCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teac_course
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TeacCourse record, @Param("example") TeacCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teac_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeacCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teac_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacCourse record);
}