package com.roy.model;

import java.util.Date;

public class Admin {

    //旧密码
    private String oldPwd;

    public String getOldPwd() {
        return oldPwd;
    }

    public void setOldPwd(String oldPwd) {
        this.oldPwd = oldPwd;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_name
     *
     * @mbg.generated
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_gender
     *
     * @mbg.generated
     */
    private String adminGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_birth
     *
     * @mbg.generated
     */
    private Date adminBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_phone
     *
     * @mbg.generated
     */
    private String adminPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_question
     *
     * @mbg.generated
     */
    private String adminQuestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_key
     *
     * @mbg.generated
     */
    private String adminKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_password
     *
     * @mbg.generated
     */
    private String adminPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.id
     *
     * @return the value of t_admin.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.id
     *
     * @param id the value for t_admin.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_name
     *
     * @return the value of t_admin.admin_name
     *
     * @mbg.generated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_name
     *
     * @param adminName the value for t_admin.admin_name
     *
     * @mbg.generated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_gender
     *
     * @return the value of t_admin.admin_gender
     *
     * @mbg.generated
     */
    public String getAdminGender() {
        return adminGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_gender
     *
     * @param adminGender the value for t_admin.admin_gender
     *
     * @mbg.generated
     */
    public void setAdminGender(String adminGender) {
        this.adminGender = adminGender == null ? null : adminGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_birth
     *
     * @return the value of t_admin.admin_birth
     *
     * @mbg.generated
     */
    public Date getAdminBirth() {
        return adminBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_birth
     *
     * @param adminBirth the value for t_admin.admin_birth
     *
     * @mbg.generated
     */
    public void setAdminBirth(Date adminBirth) {
        this.adminBirth = adminBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_phone
     *
     * @return the value of t_admin.admin_phone
     *
     * @mbg.generated
     */
    public String getAdminPhone() {
        return adminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_phone
     *
     * @param adminPhone the value for t_admin.admin_phone
     *
     * @mbg.generated
     */
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone == null ? null : adminPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_question
     *
     * @return the value of t_admin.admin_question
     *
     * @mbg.generated
     */
    public String getAdminQuestion() {
        return adminQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_question
     *
     * @param adminQuestion the value for t_admin.admin_question
     *
     * @mbg.generated
     */
    public void setAdminQuestion(String adminQuestion) {
        this.adminQuestion = adminQuestion == null ? null : adminQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_key
     *
     * @return the value of t_admin.admin_key
     *
     * @mbg.generated
     */
    public String getAdminKey() {
        return adminKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_key
     *
     * @param adminKey the value for t_admin.admin_key
     *
     * @mbg.generated
     */
    public void setAdminKey(String adminKey) {
        this.adminKey = adminKey == null ? null : adminKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_password
     *
     * @return the value of t_admin.admin_password
     *
     * @mbg.generated
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_password
     *
     * @param adminPassword the value for t_admin.admin_password
     *
     * @mbg.generated
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    public Admin() {
    }

    public Admin(String oldPwd, Long id, String adminName, String adminGender,
                 Date adminBirth, String adminPhone, String adminQuestion,
                 String adminKey, String adminPassword) {
        this.oldPwd = oldPwd;
        this.id = id;
        this.adminName = adminName;
        this.adminGender = adminGender;
        this.adminBirth = adminBirth;
        this.adminPhone = adminPhone;
        this.adminQuestion = adminQuestion;
        this.adminKey = adminKey;
        this.adminPassword = adminPassword;
    }

    @Override
    public String toString() {
        return "Admin{" +
                "oldPwd='" + oldPwd + '\'' +
                ", id=" + id +
                ", adminName='" + adminName + '\'' +
                ", adminGender='" + adminGender + '\'' +
                ", adminBirth=" + adminBirth +
                ", adminPhone='" + adminPhone + '\'' +
                ", adminQuestion='" + adminQuestion + '\'' +
                ", adminKey='" + adminKey + '\'' +
                ", adminPassword='" + adminPassword + '\'' +
                '}';
    }
}