package com.roy.model;

public class Calculate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_calculate.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_calculate.teac_course_id
     *
     * @mbg.generated
     */
    private Long teacCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_calculate.exam_id
     *
     * @mbg.generated
     */
    private Integer examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_calculate.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_calculate.dificult
     *
     * @mbg.generated
     */
    private String dificult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_calculate.answer1
     *
     * @mbg.generated
     */
    private String answer1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_calculate.answer2
     *
     * @mbg.generated
     */
    private String answer2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_calculate.answer3
     *
     * @mbg.generated
     */
    private String answer3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_calculate.calculate_id
     *
     * @mbg.generated
     */
    private String calculateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_calculate.id
     *
     * @return the value of t_calculate.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_calculate.id
     *
     * @param id the value for t_calculate.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_calculate.teac_course_id
     *
     * @return the value of t_calculate.teac_course_id
     *
     * @mbg.generated
     */
    public Long getTeacCourseId() {
        return teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_calculate.teac_course_id
     *
     * @param teacCourseId the value for t_calculate.teac_course_id
     *
     * @mbg.generated
     */
    public void setTeacCourseId(Long teacCourseId) {
        this.teacCourseId = teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_calculate.exam_id
     *
     * @return the value of t_calculate.exam_id
     *
     * @mbg.generated
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_calculate.exam_id
     *
     * @param examId the value for t_calculate.exam_id
     *
     * @mbg.generated
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_calculate.title
     *
     * @return the value of t_calculate.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_calculate.title
     *
     * @param title the value for t_calculate.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_calculate.dificult
     *
     * @return the value of t_calculate.dificult
     *
     * @mbg.generated
     */
    public String getDificult() {
        return dificult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_calculate.dificult
     *
     * @param dificult the value for t_calculate.dificult
     *
     * @mbg.generated
     */
    public void setDificult(String dificult) {
        this.dificult = dificult == null ? null : dificult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_calculate.answer1
     *
     * @return the value of t_calculate.answer1
     *
     * @mbg.generated
     */
    public String getAnswer1() {
        return answer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_calculate.answer1
     *
     * @param answer1 the value for t_calculate.answer1
     *
     * @mbg.generated
     */
    public void setAnswer1(String answer1) {
        this.answer1 = answer1 == null ? null : answer1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_calculate.answer2
     *
     * @return the value of t_calculate.answer2
     *
     * @mbg.generated
     */
    public String getAnswer2() {
        return answer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_calculate.answer2
     *
     * @param answer2 the value for t_calculate.answer2
     *
     * @mbg.generated
     */
    public void setAnswer2(String answer2) {
        this.answer2 = answer2 == null ? null : answer2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_calculate.answer3
     *
     * @return the value of t_calculate.answer3
     *
     * @mbg.generated
     */
    public String getAnswer3() {
        return answer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_calculate.answer3
     *
     * @param answer3 the value for t_calculate.answer3
     *
     * @mbg.generated
     */
    public void setAnswer3(String answer3) {
        this.answer3 = answer3 == null ? null : answer3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_calculate.calculate_id
     *
     * @return the value of t_calculate.calculate_id
     *
     * @mbg.generated
     */
    public String getCalculateId() {
        return calculateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_calculate.calculate_id
     *
     * @param calculateId the value for t_calculate.calculate_id
     *
     * @mbg.generated
     */
    public void setCalculateId(String calculateId) {
        this.calculateId = calculateId == null ? null : calculateId.trim();
    }
}