package com.roy.model;

import java.math.BigDecimal;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_num
     *
     * @mbg.generated
     */
    private String courseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_credit
     *
     * @mbg.generated
     */
    private BigDecimal courseCredit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.id
     *
     * @return the value of t_course.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.id
     *
     * @param id the value for t_course.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_num
     *
     * @return the value of t_course.course_num
     *
     * @mbg.generated
     */
    public String getCourseNum() {
        return courseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_num
     *
     * @param courseNum the value for t_course.course_num
     *
     * @mbg.generated
     */
    public void setCourseNum(String courseNum) {
        this.courseNum = courseNum == null ? null : courseNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_name
     *
     * @return the value of t_course.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_name
     *
     * @param courseName the value for t_course.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_credit
     *
     * @return the value of t_course.course_credit
     *
     * @mbg.generated
     */
    public BigDecimal getCourseCredit() {
        return courseCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_credit
     *
     * @param courseCredit the value for t_course.course_credit
     *
     * @mbg.generated
     */
    public void setCourseCredit(BigDecimal courseCredit) {
        this.courseCredit = courseCredit;
    }
}