package com.roy.model;

import java.util.Date;

public class HomeWork {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.homeWork_content
     *
     * @mbg.generated
     */
    private String homeworkContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.teac_course_id
     *
     * @mbg.generated
     */
    private Long teacCourseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.id
     *
     * @return the value of t_homework.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.id
     *
     * @param id the value for t_homework.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.homeWork_content
     *
     * @return the value of t_homework.homeWork_content
     *
     * @mbg.generated
     */
    public String getHomeworkContent() {
        return homeworkContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.homeWork_content
     *
     * @param homeworkContent the value for t_homework.homeWork_content
     *
     * @mbg.generated
     */
    public void setHomeworkContent(String homeworkContent) {
        this.homeworkContent = homeworkContent == null ? null : homeworkContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.course_name
     *
     * @return the value of t_homework.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.course_name
     *
     * @param courseName the value for t_homework.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.date
     *
     * @return the value of t_homework.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.date
     *
     * @param date the value for t_homework.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.teac_course_id
     *
     * @return the value of t_homework.teac_course_id
     *
     * @mbg.generated
     */
    public Long getTeacCourseId() {
        return teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.teac_course_id
     *
     * @param teacCourseId the value for t_homework.teac_course_id
     *
     * @mbg.generated
     */
    public void setTeacCourseId(Long teacCourseId) {
        this.teacCourseId = teacCourseId;
    }

    @Override
    public String toString() {
        return "HomeWork{" +
                "id=" + id +
                ", homeworkContent='" + homeworkContent + '\'' +
                ", courseName='" + courseName + '\'' +
                ", date=" + date +
                ", teacCourseId=" + teacCourseId +
                '}';
    }
}