package com.roy.model;

public class Judge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_judeg.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_judeg.judge_id
     *
     * @mbg.generated
     */
    private String judgeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_judeg.teac_course_id
     *
     * @mbg.generated
     */
    private Long teacCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_judeg.exam_id
     *
     * @mbg.generated
     */
    private Integer examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_judeg.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_judeg.dificult
     *
     * @mbg.generated
     */
    private String dificult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_judeg.type1
     *
     * @mbg.generated
     */
    private String type1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_judeg.type2
     *
     * @mbg.generated
     */
    private String type2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_judeg.answer
     *
     * @mbg.generated
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_judeg.id
     *
     * @return the value of t_judeg.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_judeg.id
     *
     * @param id the value for t_judeg.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_judeg.judge_id
     *
     * @return the value of t_judeg.judge_id
     *
     * @mbg.generated
     */
    public String getJudgeId() {
        return judgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_judeg.judge_id
     *
     * @param judgeId the value for t_judeg.judge_id
     *
     * @mbg.generated
     */
    public void setJudgeId(String judgeId) {
        this.judgeId = judgeId == null ? null : judgeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_judeg.teac_course_id
     *
     * @return the value of t_judeg.teac_course_id
     *
     * @mbg.generated
     */
    public Long getTeacCourseId() {
        return teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_judeg.teac_course_id
     *
     * @param teacCourseId the value for t_judeg.teac_course_id
     *
     * @mbg.generated
     */
    public void setTeacCourseId(Long teacCourseId) {
        this.teacCourseId = teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_judeg.exam_id
     *
     * @return the value of t_judeg.exam_id
     *
     * @mbg.generated
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_judeg.exam_id
     *
     * @param examId the value for t_judeg.exam_id
     *
     * @mbg.generated
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_judeg.title
     *
     * @return the value of t_judeg.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_judeg.title
     *
     * @param title the value for t_judeg.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_judeg.dificult
     *
     * @return the value of t_judeg.dificult
     *
     * @mbg.generated
     */
    public String getDificult() {
        return dificult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_judeg.dificult
     *
     * @param dificult the value for t_judeg.dificult
     *
     * @mbg.generated
     */
    public void setDificult(String dificult) {
        this.dificult = dificult == null ? null : dificult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_judeg.type1
     *
     * @return the value of t_judeg.type1
     *
     * @mbg.generated
     */
    public String getType1() {
        return type1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_judeg.type1
     *
     * @param type1 the value for t_judeg.type1
     *
     * @mbg.generated
     */
    public void setType1(String type1) {
        this.type1 = type1 == null ? null : type1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_judeg.type2
     *
     * @return the value of t_judeg.type2
     *
     * @mbg.generated
     */
    public String getType2() {
        return type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_judeg.type2
     *
     * @param type2 the value for t_judeg.type2
     *
     * @mbg.generated
     */
    public void setType2(String type2) {
        this.type2 = type2 == null ? null : type2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_judeg.answer
     *
     * @return the value of t_judeg.answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_judeg.answer
     *
     * @param answer the value for t_judeg.answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}