package com.roy.model;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Paper {
    private String courseName;
    private String teacName;
    private String stuName;


    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public String getTeacName() {
        return teacName;
    }

    public void setTeacName(String teacName) {
        this.teacName = teacName;
    }

    public String getStuName() {
        return stuName;
    }

    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.teac_course_id
     *
     * @mbg.generated
     */
    private Long teacCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.stu_id
     *
     * @mbg.generated
     */
    private Long stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.selection_ids
     *
     * @mbg.generated
     */
    private String selectionIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.multi_selection_ids
     *
     * @mbg.generated
     */
    private String multiSelectionIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.judge_ids
     *
     * @mbg.generated
     */
    private String judgeIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.fill_ids
     *
     * @mbg.generated
     */
    private String fillIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.calculate_ids
     *
     * @mbg.generated
     */
    private String calculateIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.subject_ids
     *
     * @mbg.generated
     */
    private String subjectIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.selection_answers
     *
     * @mbg.generated
     */
    private String selectionAnswers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.multi_selection_answers
     *
     * @mbg.generated
     */
    private String multiSelectionAnswers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.judge_answers
     *
     * @mbg.generated
     */
    private String judgeAnswers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.fill_answers
     *
     * @mbg.generated
     */
    private String fillAnswers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.subject_answer1
     *
     * @mbg.generated
     */
    private String subjectAnswer1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.subject_answer2
     *
     * @mbg.generated
     */
    private String subjectAnswer2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.calculate_answers
     *
     * @mbg.generated
     */
    private String calculateAnswers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.subject_answer3
     *
     * @mbg.generated
     */
    private String subjectAnswer3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.subject_answer4
     *
     * @mbg.generated
     */
    private String subjectAnswer4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.subject_answer5
     *
     * @mbg.generated
     */
    private String subjectAnswer5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.pape_state
     *
     * @mbg.generated
     */
    private Integer papeState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.total_score
     *
     * @mbg.generated
     */
    private Integer totalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.test_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date testTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.id
     *
     * @return the value of t_paper.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.id
     *
     * @param id the value for t_paper.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.teac_course_id
     *
     * @return the value of t_paper.teac_course_id
     *
     * @mbg.generated
     */
    public Long getTeacCourseId() {
        return teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.teac_course_id
     *
     * @param teacCourseId the value for t_paper.teac_course_id
     *
     * @mbg.generated
     */
    public void setTeacCourseId(Long teacCourseId) {
        this.teacCourseId = teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.stu_id
     *
     * @return the value of t_paper.stu_id
     *
     * @mbg.generated
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.stu_id
     *
     * @param stuId the value for t_paper.stu_id
     *
     * @mbg.generated
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.selection_ids
     *
     * @return the value of t_paper.selection_ids
     *
     * @mbg.generated
     */
    public String getSelectionIds() {
        return selectionIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.selection_ids
     *
     * @param selectionIds the value for t_paper.selection_ids
     *
     * @mbg.generated
     */
    public void setSelectionIds(String selectionIds) {
        this.selectionIds = selectionIds == null ? null : selectionIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.multi_selection_ids
     *
     * @return the value of t_paper.multi_selection_ids
     *
     * @mbg.generated
     */
    public String getMultiSelectionIds() {
        return multiSelectionIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.multi_selection_ids
     *
     * @param multiSelectionIds the value for t_paper.multi_selection_ids
     *
     * @mbg.generated
     */
    public void setMultiSelectionIds(String multiSelectionIds) {
        this.multiSelectionIds = multiSelectionIds == null ? null : multiSelectionIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.judge_ids
     *
     * @return the value of t_paper.judge_ids
     *
     * @mbg.generated
     */
    public String getJudgeIds() {
        return judgeIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.judge_ids
     *
     * @param judgeIds the value for t_paper.judge_ids
     *
     * @mbg.generated
     */
    public void setJudgeIds(String judgeIds) {
        this.judgeIds = judgeIds == null ? null : judgeIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.fill_ids
     *
     * @return the value of t_paper.fill_ids
     *
     * @mbg.generated
     */
    public String getFillIds() {
        return fillIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.fill_ids
     *
     * @param fillIds the value for t_paper.fill_ids
     *
     * @mbg.generated
     */
    public void setFillIds(String fillIds) {
        this.fillIds = fillIds == null ? null : fillIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.calculate_ids
     *
     * @return the value of t_paper.calculate_ids
     *
     * @mbg.generated
     */
    public String getCalculateIds() {
        return calculateIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.calculate_ids
     *
     * @param calculateIds the value for t_paper.calculate_ids
     *
     * @mbg.generated
     */
    public void setCalculateIds(String calculateIds) {
        this.calculateIds = calculateIds == null ? null : calculateIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.subject_ids
     *
     * @return the value of t_paper.subject_ids
     *
     * @mbg.generated
     */
    public String getSubjectIds() {
        return subjectIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.subject_ids
     *
     * @param subjectIds the value for t_paper.subject_ids
     *
     * @mbg.generated
     */
    public void setSubjectIds(String subjectIds) {
        this.subjectIds = subjectIds == null ? null : subjectIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.selection_answers
     *
     * @return the value of t_paper.selection_answers
     *
     * @mbg.generated
     */
    public String getSelectionAnswers() {
        return selectionAnswers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.selection_answers
     *
     * @param selectionAnswers the value for t_paper.selection_answers
     *
     * @mbg.generated
     */
    public void setSelectionAnswers(String selectionAnswers) {
        this.selectionAnswers = selectionAnswers == null ? null : selectionAnswers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.multi_selection_answers
     *
     * @return the value of t_paper.multi_selection_answers
     *
     * @mbg.generated
     */
    public String getMultiSelectionAnswers() {
        return multiSelectionAnswers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.multi_selection_answers
     *
     * @param multiSelectionAnswers the value for t_paper.multi_selection_answers
     *
     * @mbg.generated
     */
    public void setMultiSelectionAnswers(String multiSelectionAnswers) {
        this.multiSelectionAnswers = multiSelectionAnswers == null ? null : multiSelectionAnswers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.judge_answers
     *
     * @return the value of t_paper.judge_answers
     *
     * @mbg.generated
     */
    public String getJudgeAnswers() {
        return judgeAnswers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.judge_answers
     *
     * @param judgeAnswers the value for t_paper.judge_answers
     *
     * @mbg.generated
     */
    public void setJudgeAnswers(String judgeAnswers) {
        this.judgeAnswers = judgeAnswers == null ? null : judgeAnswers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.fill_answers
     *
     * @return the value of t_paper.fill_answers
     *
     * @mbg.generated
     */
    public String getFillAnswers() {
        return fillAnswers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.fill_answers
     *
     * @param fillAnswers the value for t_paper.fill_answers
     *
     * @mbg.generated
     */
    public void setFillAnswers(String fillAnswers) {
        this.fillAnswers = fillAnswers == null ? null : fillAnswers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.subject_answer1
     *
     * @return the value of t_paper.subject_answer1
     *
     * @mbg.generated
     */
    public String getSubjectAnswer1() {
        return subjectAnswer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.subject_answer1
     *
     * @param subjectAnswer1 the value for t_paper.subject_answer1
     *
     * @mbg.generated
     */
    public void setSubjectAnswer1(String subjectAnswer1) {
        this.subjectAnswer1 = subjectAnswer1 == null ? null : subjectAnswer1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.subject_answer2
     *
     * @return the value of t_paper.subject_answer2
     *
     * @mbg.generated
     */
    public String getSubjectAnswer2() {
        return subjectAnswer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.subject_answer2
     *
     * @param subjectAnswer2 the value for t_paper.subject_answer2
     *
     * @mbg.generated
     */
    public void setSubjectAnswer2(String subjectAnswer2) {
        this.subjectAnswer2 = subjectAnswer2 == null ? null : subjectAnswer2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.calculate_answers
     *
     * @return the value of t_paper.calculate_answers
     *
     * @mbg.generated
     */
    public String getCalculateAnswers() {
        return calculateAnswers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.calculate_answers
     *
     * @param calculateAnswers the value for t_paper.calculate_answers
     *
     * @mbg.generated
     */
    public void setCalculateAnswers(String calculateAnswers) {
        this.calculateAnswers = calculateAnswers == null ? null : calculateAnswers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.subject_answer3
     *
     * @return the value of t_paper.subject_answer3
     *
     * @mbg.generated
     */
    public String getSubjectAnswer3() {
        return subjectAnswer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.subject_answer3
     *
     * @param subjectAnswer3 the value for t_paper.subject_answer3
     *
     * @mbg.generated
     */
    public void setSubjectAnswer3(String subjectAnswer3) {
        this.subjectAnswer3 = subjectAnswer3 == null ? null : subjectAnswer3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.subject_answer4
     *
     * @return the value of t_paper.subject_answer4
     *
     * @mbg.generated
     */
    public String getSubjectAnswer4() {
        return subjectAnswer4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.subject_answer4
     *
     * @param subjectAnswer4 the value for t_paper.subject_answer4
     *
     * @mbg.generated
     */
    public void setSubjectAnswer4(String subjectAnswer4) {
        this.subjectAnswer4 = subjectAnswer4 == null ? null : subjectAnswer4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.subject_answer5
     *
     * @return the value of t_paper.subject_answer5
     *
     * @mbg.generated
     */
    public String getSubjectAnswer5() {
        return subjectAnswer5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.subject_answer5
     *
     * @param subjectAnswer5 the value for t_paper.subject_answer5
     *
     * @mbg.generated
     */
    public void setSubjectAnswer5(String subjectAnswer5) {
        this.subjectAnswer5 = subjectAnswer5 == null ? null : subjectAnswer5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.pape_state
     *
     * @return the value of t_paper.pape_state
     *
     * @mbg.generated
     */
    public Integer getPapeState() {
        return papeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.pape_state
     *
     * @param papeState the value for t_paper.pape_state
     *
     * @mbg.generated
     */
    public void setPapeState(Integer papeState) {
        this.papeState = papeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.total_score
     *
     * @return the value of t_paper.total_score
     *
     * @mbg.generated
     */
    public Integer getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.total_score
     *
     * @param totalScore the value for t_paper.total_score
     *
     * @mbg.generated
     */
    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.test_time
     *
     * @return the value of t_paper.test_time
     *
     * @mbg.generated
     */
    public Date getTestTime() {
        return testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.test_time
     *
     * @param testTime the value for t_paper.test_time
     *
     * @mbg.generated
     */
    public void setTestTime(Date testTime) {
        this.testTime = testTime;
    }

    public Paper() {
    }
    public Paper(Long teacCourseId, Long stuId, String selectionIds,
                 String judgeIds, String fillIds, String calculateIds,String selIds,
                 String subjectIds, Date testTime) {
        this.teacCourseId = teacCourseId;
        this.stuId = stuId;
        this.selectionIds = selectionIds;
        this.judgeIds = judgeIds;
        this.fillIds = fillIds;
        this.selectionIds = selIds;
        this.calculateIds = calculateIds;
        this.subjectIds = subjectIds;
        this.testTime = testTime;
    }

    public Paper(String courseName, String teacName, String stuName,
                 Long id, Long teacCourseId, Long stuId, String selectionIds,
                 String multiSelectionIds, String judgeIds, String fillIds,
                 String calculateIds, String subjectIds, String selectionAnswers,
                 String multiSelectionAnswers, String judgeAnswers, String fillAnswers,
                 String subjectAnswer1, String subjectAnswer2, String calculateAnswers,
                 String subjectAnswer3, String subjectAnswer4, String subjectAnswer5,
                 Integer papeState, Integer totalScore, Date testTime) {
        this.courseName = courseName;
        this.teacName = teacName;
        this.stuName = stuName;
        this.id = id;
        this.teacCourseId = teacCourseId;
        this.stuId = stuId;
        this.selectionIds = selectionIds;
        this.multiSelectionIds = multiSelectionIds;
        this.judgeIds = judgeIds;
        this.fillIds = fillIds;
        this.calculateIds = calculateIds;
        this.subjectIds = subjectIds;
        this.selectionAnswers = selectionAnswers;
        this.multiSelectionAnswers = multiSelectionAnswers;
        this.judgeAnswers = judgeAnswers;
        this.fillAnswers = fillAnswers;
        this.subjectAnswer1 = subjectAnswer1;
        this.subjectAnswer2 = subjectAnswer2;
        this.calculateAnswers = calculateAnswers;
        this.subjectAnswer3 = subjectAnswer3;
        this.subjectAnswer4 = subjectAnswer4;
        this.subjectAnswer5 = subjectAnswer5;
        this.papeState = papeState;
        this.totalScore = totalScore;
        this.testTime = testTime;
    }

    @Override
    public String toString() {
        return "Paper{" +
                "courseName='" + courseName + '\'' +
                ", teacName='" + teacName + '\'' +
                ", stuName='" + stuName + '\'' +
                ", id=" + id +
                ", teacCourseId=" + teacCourseId +
                ", stuId=" + stuId +
                ", selectionIds='" + selectionIds + '\'' +
                ", multiSelectionIds='" + multiSelectionIds + '\'' +
                ", judgeIds='" + judgeIds + '\'' +
                ", fillIds='" + fillIds + '\'' +
                ", calculateIds='" + calculateIds + '\'' +
                ", subjectIds='" + subjectIds + '\'' +
                ", selectionAnswers='" + selectionAnswers + '\'' +
                ", multiSelectionAnswers='" + multiSelectionAnswers + '\'' +
                ", judgeAnswers='" + judgeAnswers + '\'' +
                ", fillAnswers='" + fillAnswers + '\'' +
                ", subjectAnswer1='" + subjectAnswer1 + '\'' +
                ", subjectAnswer2='" + subjectAnswer2 + '\'' +
                ", calculateAnswers='" + calculateAnswers + '\'' +
                ", subjectAnswer3='" + subjectAnswer3 + '\'' +
                ", subjectAnswer4='" + subjectAnswer4 + '\'' +
                ", subjectAnswer5='" + subjectAnswer5 + '\'' +
                ", papeState=" + papeState +
                ", totalScore=" + totalScore +
                ", testTime=" + testTime +
                '}';
    }
}