package com.roy.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PaperExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    public PaperExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTeacCourseIdIsNull() {
            addCriterion("teac_course_id is null");
            return (Criteria) this;
        }

        public Criteria andTeacCourseIdIsNotNull() {
            addCriterion("teac_course_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeacCourseIdEqualTo(Long value) {
            addCriterion("teac_course_id =", value, "teacCourseId");
            return (Criteria) this;
        }

        public Criteria andTeacCourseIdNotEqualTo(Long value) {
            addCriterion("teac_course_id <>", value, "teacCourseId");
            return (Criteria) this;
        }

        public Criteria andTeacCourseIdGreaterThan(Long value) {
            addCriterion("teac_course_id >", value, "teacCourseId");
            return (Criteria) this;
        }

        public Criteria andTeacCourseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("teac_course_id >=", value, "teacCourseId");
            return (Criteria) this;
        }

        public Criteria andTeacCourseIdLessThan(Long value) {
            addCriterion("teac_course_id <", value, "teacCourseId");
            return (Criteria) this;
        }

        public Criteria andTeacCourseIdLessThanOrEqualTo(Long value) {
            addCriterion("teac_course_id <=", value, "teacCourseId");
            return (Criteria) this;
        }

        public Criteria andTeacCourseIdIn(List<Long> values) {
            addCriterion("teac_course_id in", values, "teacCourseId");
            return (Criteria) this;
        }

        public Criteria andTeacCourseIdNotIn(List<Long> values) {
            addCriterion("teac_course_id not in", values, "teacCourseId");
            return (Criteria) this;
        }

        public Criteria andTeacCourseIdBetween(Long value1, Long value2) {
            addCriterion("teac_course_id between", value1, value2, "teacCourseId");
            return (Criteria) this;
        }

        public Criteria andTeacCourseIdNotBetween(Long value1, Long value2) {
            addCriterion("teac_course_id not between", value1, value2, "teacCourseId");
            return (Criteria) this;
        }

        public Criteria andStuIdIsNull() {
            addCriterion("stu_id is null");
            return (Criteria) this;
        }

        public Criteria andStuIdIsNotNull() {
            addCriterion("stu_id is not null");
            return (Criteria) this;
        }

        public Criteria andStuIdEqualTo(Long value) {
            addCriterion("stu_id =", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotEqualTo(Long value) {
            addCriterion("stu_id <>", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThan(Long value) {
            addCriterion("stu_id >", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("stu_id >=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThan(Long value) {
            addCriterion("stu_id <", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThanOrEqualTo(Long value) {
            addCriterion("stu_id <=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdIn(List<Long> values) {
            addCriterion("stu_id in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotIn(List<Long> values) {
            addCriterion("stu_id not in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdBetween(Long value1, Long value2) {
            addCriterion("stu_id between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotBetween(Long value1, Long value2) {
            addCriterion("stu_id not between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsIsNull() {
            addCriterion("selection_ids is null");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsIsNotNull() {
            addCriterion("selection_ids is not null");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsEqualTo(String value) {
            addCriterion("selection_ids =", value, "selectionIds");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsNotEqualTo(String value) {
            addCriterion("selection_ids <>", value, "selectionIds");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsGreaterThan(String value) {
            addCriterion("selection_ids >", value, "selectionIds");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsGreaterThanOrEqualTo(String value) {
            addCriterion("selection_ids >=", value, "selectionIds");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsLessThan(String value) {
            addCriterion("selection_ids <", value, "selectionIds");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsLessThanOrEqualTo(String value) {
            addCriterion("selection_ids <=", value, "selectionIds");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsLike(String value) {
            addCriterion("selection_ids like", value, "selectionIds");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsNotLike(String value) {
            addCriterion("selection_ids not like", value, "selectionIds");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsIn(List<String> values) {
            addCriterion("selection_ids in", values, "selectionIds");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsNotIn(List<String> values) {
            addCriterion("selection_ids not in", values, "selectionIds");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsBetween(String value1, String value2) {
            addCriterion("selection_ids between", value1, value2, "selectionIds");
            return (Criteria) this;
        }

        public Criteria andSelectionIdsNotBetween(String value1, String value2) {
            addCriterion("selection_ids not between", value1, value2, "selectionIds");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsIsNull() {
            addCriterion("multi_selection_ids is null");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsIsNotNull() {
            addCriterion("multi_selection_ids is not null");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsEqualTo(String value) {
            addCriterion("multi_selection_ids =", value, "multiSelectionIds");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsNotEqualTo(String value) {
            addCriterion("multi_selection_ids <>", value, "multiSelectionIds");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsGreaterThan(String value) {
            addCriterion("multi_selection_ids >", value, "multiSelectionIds");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsGreaterThanOrEqualTo(String value) {
            addCriterion("multi_selection_ids >=", value, "multiSelectionIds");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsLessThan(String value) {
            addCriterion("multi_selection_ids <", value, "multiSelectionIds");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsLessThanOrEqualTo(String value) {
            addCriterion("multi_selection_ids <=", value, "multiSelectionIds");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsLike(String value) {
            addCriterion("multi_selection_ids like", value, "multiSelectionIds");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsNotLike(String value) {
            addCriterion("multi_selection_ids not like", value, "multiSelectionIds");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsIn(List<String> values) {
            addCriterion("multi_selection_ids in", values, "multiSelectionIds");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsNotIn(List<String> values) {
            addCriterion("multi_selection_ids not in", values, "multiSelectionIds");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsBetween(String value1, String value2) {
            addCriterion("multi_selection_ids between", value1, value2, "multiSelectionIds");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionIdsNotBetween(String value1, String value2) {
            addCriterion("multi_selection_ids not between", value1, value2, "multiSelectionIds");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsIsNull() {
            addCriterion("judge_ids is null");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsIsNotNull() {
            addCriterion("judge_ids is not null");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsEqualTo(String value) {
            addCriterion("judge_ids =", value, "judgeIds");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsNotEqualTo(String value) {
            addCriterion("judge_ids <>", value, "judgeIds");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsGreaterThan(String value) {
            addCriterion("judge_ids >", value, "judgeIds");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsGreaterThanOrEqualTo(String value) {
            addCriterion("judge_ids >=", value, "judgeIds");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsLessThan(String value) {
            addCriterion("judge_ids <", value, "judgeIds");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsLessThanOrEqualTo(String value) {
            addCriterion("judge_ids <=", value, "judgeIds");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsLike(String value) {
            addCriterion("judge_ids like", value, "judgeIds");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsNotLike(String value) {
            addCriterion("judge_ids not like", value, "judgeIds");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsIn(List<String> values) {
            addCriterion("judge_ids in", values, "judgeIds");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsNotIn(List<String> values) {
            addCriterion("judge_ids not in", values, "judgeIds");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsBetween(String value1, String value2) {
            addCriterion("judge_ids between", value1, value2, "judgeIds");
            return (Criteria) this;
        }

        public Criteria andJudgeIdsNotBetween(String value1, String value2) {
            addCriterion("judge_ids not between", value1, value2, "judgeIds");
            return (Criteria) this;
        }

        public Criteria andFillIdsIsNull() {
            addCriterion("fill_ids is null");
            return (Criteria) this;
        }

        public Criteria andFillIdsIsNotNull() {
            addCriterion("fill_ids is not null");
            return (Criteria) this;
        }

        public Criteria andFillIdsEqualTo(String value) {
            addCriterion("fill_ids =", value, "fillIds");
            return (Criteria) this;
        }

        public Criteria andFillIdsNotEqualTo(String value) {
            addCriterion("fill_ids <>", value, "fillIds");
            return (Criteria) this;
        }

        public Criteria andFillIdsGreaterThan(String value) {
            addCriterion("fill_ids >", value, "fillIds");
            return (Criteria) this;
        }

        public Criteria andFillIdsGreaterThanOrEqualTo(String value) {
            addCriterion("fill_ids >=", value, "fillIds");
            return (Criteria) this;
        }

        public Criteria andFillIdsLessThan(String value) {
            addCriterion("fill_ids <", value, "fillIds");
            return (Criteria) this;
        }

        public Criteria andFillIdsLessThanOrEqualTo(String value) {
            addCriterion("fill_ids <=", value, "fillIds");
            return (Criteria) this;
        }

        public Criteria andFillIdsLike(String value) {
            addCriterion("fill_ids like", value, "fillIds");
            return (Criteria) this;
        }

        public Criteria andFillIdsNotLike(String value) {
            addCriterion("fill_ids not like", value, "fillIds");
            return (Criteria) this;
        }

        public Criteria andFillIdsIn(List<String> values) {
            addCriterion("fill_ids in", values, "fillIds");
            return (Criteria) this;
        }

        public Criteria andFillIdsNotIn(List<String> values) {
            addCriterion("fill_ids not in", values, "fillIds");
            return (Criteria) this;
        }

        public Criteria andFillIdsBetween(String value1, String value2) {
            addCriterion("fill_ids between", value1, value2, "fillIds");
            return (Criteria) this;
        }

        public Criteria andFillIdsNotBetween(String value1, String value2) {
            addCriterion("fill_ids not between", value1, value2, "fillIds");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsIsNull() {
            addCriterion("calculate_ids is null");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsIsNotNull() {
            addCriterion("calculate_ids is not null");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsEqualTo(String value) {
            addCriterion("calculate_ids =", value, "calculateIds");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsNotEqualTo(String value) {
            addCriterion("calculate_ids <>", value, "calculateIds");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsGreaterThan(String value) {
            addCriterion("calculate_ids >", value, "calculateIds");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsGreaterThanOrEqualTo(String value) {
            addCriterion("calculate_ids >=", value, "calculateIds");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsLessThan(String value) {
            addCriterion("calculate_ids <", value, "calculateIds");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsLessThanOrEqualTo(String value) {
            addCriterion("calculate_ids <=", value, "calculateIds");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsLike(String value) {
            addCriterion("calculate_ids like", value, "calculateIds");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsNotLike(String value) {
            addCriterion("calculate_ids not like", value, "calculateIds");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsIn(List<String> values) {
            addCriterion("calculate_ids in", values, "calculateIds");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsNotIn(List<String> values) {
            addCriterion("calculate_ids not in", values, "calculateIds");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsBetween(String value1, String value2) {
            addCriterion("calculate_ids between", value1, value2, "calculateIds");
            return (Criteria) this;
        }

        public Criteria andCalculateIdsNotBetween(String value1, String value2) {
            addCriterion("calculate_ids not between", value1, value2, "calculateIds");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsIsNull() {
            addCriterion("subject_ids is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsIsNotNull() {
            addCriterion("subject_ids is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsEqualTo(String value) {
            addCriterion("subject_ids =", value, "subjectIds");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsNotEqualTo(String value) {
            addCriterion("subject_ids <>", value, "subjectIds");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsGreaterThan(String value) {
            addCriterion("subject_ids >", value, "subjectIds");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsGreaterThanOrEqualTo(String value) {
            addCriterion("subject_ids >=", value, "subjectIds");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsLessThan(String value) {
            addCriterion("subject_ids <", value, "subjectIds");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsLessThanOrEqualTo(String value) {
            addCriterion("subject_ids <=", value, "subjectIds");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsLike(String value) {
            addCriterion("subject_ids like", value, "subjectIds");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsNotLike(String value) {
            addCriterion("subject_ids not like", value, "subjectIds");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsIn(List<String> values) {
            addCriterion("subject_ids in", values, "subjectIds");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsNotIn(List<String> values) {
            addCriterion("subject_ids not in", values, "subjectIds");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsBetween(String value1, String value2) {
            addCriterion("subject_ids between", value1, value2, "subjectIds");
            return (Criteria) this;
        }

        public Criteria andSubjectIdsNotBetween(String value1, String value2) {
            addCriterion("subject_ids not between", value1, value2, "subjectIds");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersIsNull() {
            addCriterion("selection_answers is null");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersIsNotNull() {
            addCriterion("selection_answers is not null");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersEqualTo(String value) {
            addCriterion("selection_answers =", value, "selectionAnswers");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersNotEqualTo(String value) {
            addCriterion("selection_answers <>", value, "selectionAnswers");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersGreaterThan(String value) {
            addCriterion("selection_answers >", value, "selectionAnswers");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersGreaterThanOrEqualTo(String value) {
            addCriterion("selection_answers >=", value, "selectionAnswers");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersLessThan(String value) {
            addCriterion("selection_answers <", value, "selectionAnswers");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersLessThanOrEqualTo(String value) {
            addCriterion("selection_answers <=", value, "selectionAnswers");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersLike(String value) {
            addCriterion("selection_answers like", value, "selectionAnswers");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersNotLike(String value) {
            addCriterion("selection_answers not like", value, "selectionAnswers");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersIn(List<String> values) {
            addCriterion("selection_answers in", values, "selectionAnswers");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersNotIn(List<String> values) {
            addCriterion("selection_answers not in", values, "selectionAnswers");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersBetween(String value1, String value2) {
            addCriterion("selection_answers between", value1, value2, "selectionAnswers");
            return (Criteria) this;
        }

        public Criteria andSelectionAnswersNotBetween(String value1, String value2) {
            addCriterion("selection_answers not between", value1, value2, "selectionAnswers");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersIsNull() {
            addCriterion("multi_selection_answers is null");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersIsNotNull() {
            addCriterion("multi_selection_answers is not null");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersEqualTo(String value) {
            addCriterion("multi_selection_answers =", value, "multiSelectionAnswers");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersNotEqualTo(String value) {
            addCriterion("multi_selection_answers <>", value, "multiSelectionAnswers");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersGreaterThan(String value) {
            addCriterion("multi_selection_answers >", value, "multiSelectionAnswers");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersGreaterThanOrEqualTo(String value) {
            addCriterion("multi_selection_answers >=", value, "multiSelectionAnswers");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersLessThan(String value) {
            addCriterion("multi_selection_answers <", value, "multiSelectionAnswers");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersLessThanOrEqualTo(String value) {
            addCriterion("multi_selection_answers <=", value, "multiSelectionAnswers");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersLike(String value) {
            addCriterion("multi_selection_answers like", value, "multiSelectionAnswers");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersNotLike(String value) {
            addCriterion("multi_selection_answers not like", value, "multiSelectionAnswers");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersIn(List<String> values) {
            addCriterion("multi_selection_answers in", values, "multiSelectionAnswers");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersNotIn(List<String> values) {
            addCriterion("multi_selection_answers not in", values, "multiSelectionAnswers");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersBetween(String value1, String value2) {
            addCriterion("multi_selection_answers between", value1, value2, "multiSelectionAnswers");
            return (Criteria) this;
        }

        public Criteria andMultiSelectionAnswersNotBetween(String value1, String value2) {
            addCriterion("multi_selection_answers not between", value1, value2, "multiSelectionAnswers");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersIsNull() {
            addCriterion("judge_answers is null");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersIsNotNull() {
            addCriterion("judge_answers is not null");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersEqualTo(String value) {
            addCriterion("judge_answers =", value, "judgeAnswers");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersNotEqualTo(String value) {
            addCriterion("judge_answers <>", value, "judgeAnswers");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersGreaterThan(String value) {
            addCriterion("judge_answers >", value, "judgeAnswers");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersGreaterThanOrEqualTo(String value) {
            addCriterion("judge_answers >=", value, "judgeAnswers");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersLessThan(String value) {
            addCriterion("judge_answers <", value, "judgeAnswers");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersLessThanOrEqualTo(String value) {
            addCriterion("judge_answers <=", value, "judgeAnswers");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersLike(String value) {
            addCriterion("judge_answers like", value, "judgeAnswers");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersNotLike(String value) {
            addCriterion("judge_answers not like", value, "judgeAnswers");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersIn(List<String> values) {
            addCriterion("judge_answers in", values, "judgeAnswers");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersNotIn(List<String> values) {
            addCriterion("judge_answers not in", values, "judgeAnswers");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersBetween(String value1, String value2) {
            addCriterion("judge_answers between", value1, value2, "judgeAnswers");
            return (Criteria) this;
        }

        public Criteria andJudgeAnswersNotBetween(String value1, String value2) {
            addCriterion("judge_answers not between", value1, value2, "judgeAnswers");
            return (Criteria) this;
        }

        public Criteria andFillAnswersIsNull() {
            addCriterion("fill_answers is null");
            return (Criteria) this;
        }

        public Criteria andFillAnswersIsNotNull() {
            addCriterion("fill_answers is not null");
            return (Criteria) this;
        }

        public Criteria andFillAnswersEqualTo(String value) {
            addCriterion("fill_answers =", value, "fillAnswers");
            return (Criteria) this;
        }

        public Criteria andFillAnswersNotEqualTo(String value) {
            addCriterion("fill_answers <>", value, "fillAnswers");
            return (Criteria) this;
        }

        public Criteria andFillAnswersGreaterThan(String value) {
            addCriterion("fill_answers >", value, "fillAnswers");
            return (Criteria) this;
        }

        public Criteria andFillAnswersGreaterThanOrEqualTo(String value) {
            addCriterion("fill_answers >=", value, "fillAnswers");
            return (Criteria) this;
        }

        public Criteria andFillAnswersLessThan(String value) {
            addCriterion("fill_answers <", value, "fillAnswers");
            return (Criteria) this;
        }

        public Criteria andFillAnswersLessThanOrEqualTo(String value) {
            addCriterion("fill_answers <=", value, "fillAnswers");
            return (Criteria) this;
        }

        public Criteria andFillAnswersLike(String value) {
            addCriterion("fill_answers like", value, "fillAnswers");
            return (Criteria) this;
        }

        public Criteria andFillAnswersNotLike(String value) {
            addCriterion("fill_answers not like", value, "fillAnswers");
            return (Criteria) this;
        }

        public Criteria andFillAnswersIn(List<String> values) {
            addCriterion("fill_answers in", values, "fillAnswers");
            return (Criteria) this;
        }

        public Criteria andFillAnswersNotIn(List<String> values) {
            addCriterion("fill_answers not in", values, "fillAnswers");
            return (Criteria) this;
        }

        public Criteria andFillAnswersBetween(String value1, String value2) {
            addCriterion("fill_answers between", value1, value2, "fillAnswers");
            return (Criteria) this;
        }

        public Criteria andFillAnswersNotBetween(String value1, String value2) {
            addCriterion("fill_answers not between", value1, value2, "fillAnswers");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1IsNull() {
            addCriterion("subject_answer1 is null");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1IsNotNull() {
            addCriterion("subject_answer1 is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1EqualTo(String value) {
            addCriterion("subject_answer1 =", value, "subjectAnswer1");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1NotEqualTo(String value) {
            addCriterion("subject_answer1 <>", value, "subjectAnswer1");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1GreaterThan(String value) {
            addCriterion("subject_answer1 >", value, "subjectAnswer1");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1GreaterThanOrEqualTo(String value) {
            addCriterion("subject_answer1 >=", value, "subjectAnswer1");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1LessThan(String value) {
            addCriterion("subject_answer1 <", value, "subjectAnswer1");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1LessThanOrEqualTo(String value) {
            addCriterion("subject_answer1 <=", value, "subjectAnswer1");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1Like(String value) {
            addCriterion("subject_answer1 like", value, "subjectAnswer1");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1NotLike(String value) {
            addCriterion("subject_answer1 not like", value, "subjectAnswer1");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1In(List<String> values) {
            addCriterion("subject_answer1 in", values, "subjectAnswer1");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1NotIn(List<String> values) {
            addCriterion("subject_answer1 not in", values, "subjectAnswer1");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1Between(String value1, String value2) {
            addCriterion("subject_answer1 between", value1, value2, "subjectAnswer1");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer1NotBetween(String value1, String value2) {
            addCriterion("subject_answer1 not between", value1, value2, "subjectAnswer1");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2IsNull() {
            addCriterion("subject_answer2 is null");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2IsNotNull() {
            addCriterion("subject_answer2 is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2EqualTo(String value) {
            addCriterion("subject_answer2 =", value, "subjectAnswer2");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2NotEqualTo(String value) {
            addCriterion("subject_answer2 <>", value, "subjectAnswer2");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2GreaterThan(String value) {
            addCriterion("subject_answer2 >", value, "subjectAnswer2");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2GreaterThanOrEqualTo(String value) {
            addCriterion("subject_answer2 >=", value, "subjectAnswer2");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2LessThan(String value) {
            addCriterion("subject_answer2 <", value, "subjectAnswer2");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2LessThanOrEqualTo(String value) {
            addCriterion("subject_answer2 <=", value, "subjectAnswer2");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2Like(String value) {
            addCriterion("subject_answer2 like", value, "subjectAnswer2");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2NotLike(String value) {
            addCriterion("subject_answer2 not like", value, "subjectAnswer2");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2In(List<String> values) {
            addCriterion("subject_answer2 in", values, "subjectAnswer2");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2NotIn(List<String> values) {
            addCriterion("subject_answer2 not in", values, "subjectAnswer2");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2Between(String value1, String value2) {
            addCriterion("subject_answer2 between", value1, value2, "subjectAnswer2");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer2NotBetween(String value1, String value2) {
            addCriterion("subject_answer2 not between", value1, value2, "subjectAnswer2");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersIsNull() {
            addCriterion("calculate_answers is null");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersIsNotNull() {
            addCriterion("calculate_answers is not null");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersEqualTo(String value) {
            addCriterion("calculate_answers =", value, "calculateAnswers");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersNotEqualTo(String value) {
            addCriterion("calculate_answers <>", value, "calculateAnswers");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersGreaterThan(String value) {
            addCriterion("calculate_answers >", value, "calculateAnswers");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersGreaterThanOrEqualTo(String value) {
            addCriterion("calculate_answers >=", value, "calculateAnswers");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersLessThan(String value) {
            addCriterion("calculate_answers <", value, "calculateAnswers");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersLessThanOrEqualTo(String value) {
            addCriterion("calculate_answers <=", value, "calculateAnswers");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersLike(String value) {
            addCriterion("calculate_answers like", value, "calculateAnswers");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersNotLike(String value) {
            addCriterion("calculate_answers not like", value, "calculateAnswers");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersIn(List<String> values) {
            addCriterion("calculate_answers in", values, "calculateAnswers");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersNotIn(List<String> values) {
            addCriterion("calculate_answers not in", values, "calculateAnswers");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersBetween(String value1, String value2) {
            addCriterion("calculate_answers between", value1, value2, "calculateAnswers");
            return (Criteria) this;
        }

        public Criteria andCalculateAnswersNotBetween(String value1, String value2) {
            addCriterion("calculate_answers not between", value1, value2, "calculateAnswers");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3IsNull() {
            addCriterion("subject_answer3 is null");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3IsNotNull() {
            addCriterion("subject_answer3 is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3EqualTo(String value) {
            addCriterion("subject_answer3 =", value, "subjectAnswer3");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3NotEqualTo(String value) {
            addCriterion("subject_answer3 <>", value, "subjectAnswer3");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3GreaterThan(String value) {
            addCriterion("subject_answer3 >", value, "subjectAnswer3");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3GreaterThanOrEqualTo(String value) {
            addCriterion("subject_answer3 >=", value, "subjectAnswer3");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3LessThan(String value) {
            addCriterion("subject_answer3 <", value, "subjectAnswer3");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3LessThanOrEqualTo(String value) {
            addCriterion("subject_answer3 <=", value, "subjectAnswer3");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3Like(String value) {
            addCriterion("subject_answer3 like", value, "subjectAnswer3");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3NotLike(String value) {
            addCriterion("subject_answer3 not like", value, "subjectAnswer3");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3In(List<String> values) {
            addCriterion("subject_answer3 in", values, "subjectAnswer3");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3NotIn(List<String> values) {
            addCriterion("subject_answer3 not in", values, "subjectAnswer3");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3Between(String value1, String value2) {
            addCriterion("subject_answer3 between", value1, value2, "subjectAnswer3");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer3NotBetween(String value1, String value2) {
            addCriterion("subject_answer3 not between", value1, value2, "subjectAnswer3");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4IsNull() {
            addCriterion("subject_answer4 is null");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4IsNotNull() {
            addCriterion("subject_answer4 is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4EqualTo(String value) {
            addCriterion("subject_answer4 =", value, "subjectAnswer4");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4NotEqualTo(String value) {
            addCriterion("subject_answer4 <>", value, "subjectAnswer4");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4GreaterThan(String value) {
            addCriterion("subject_answer4 >", value, "subjectAnswer4");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4GreaterThanOrEqualTo(String value) {
            addCriterion("subject_answer4 >=", value, "subjectAnswer4");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4LessThan(String value) {
            addCriterion("subject_answer4 <", value, "subjectAnswer4");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4LessThanOrEqualTo(String value) {
            addCriterion("subject_answer4 <=", value, "subjectAnswer4");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4Like(String value) {
            addCriterion("subject_answer4 like", value, "subjectAnswer4");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4NotLike(String value) {
            addCriterion("subject_answer4 not like", value, "subjectAnswer4");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4In(List<String> values) {
            addCriterion("subject_answer4 in", values, "subjectAnswer4");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4NotIn(List<String> values) {
            addCriterion("subject_answer4 not in", values, "subjectAnswer4");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4Between(String value1, String value2) {
            addCriterion("subject_answer4 between", value1, value2, "subjectAnswer4");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer4NotBetween(String value1, String value2) {
            addCriterion("subject_answer4 not between", value1, value2, "subjectAnswer4");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5IsNull() {
            addCriterion("subject_answer5 is null");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5IsNotNull() {
            addCriterion("subject_answer5 is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5EqualTo(String value) {
            addCriterion("subject_answer5 =", value, "subjectAnswer5");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5NotEqualTo(String value) {
            addCriterion("subject_answer5 <>", value, "subjectAnswer5");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5GreaterThan(String value) {
            addCriterion("subject_answer5 >", value, "subjectAnswer5");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5GreaterThanOrEqualTo(String value) {
            addCriterion("subject_answer5 >=", value, "subjectAnswer5");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5LessThan(String value) {
            addCriterion("subject_answer5 <", value, "subjectAnswer5");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5LessThanOrEqualTo(String value) {
            addCriterion("subject_answer5 <=", value, "subjectAnswer5");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5Like(String value) {
            addCriterion("subject_answer5 like", value, "subjectAnswer5");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5NotLike(String value) {
            addCriterion("subject_answer5 not like", value, "subjectAnswer5");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5In(List<String> values) {
            addCriterion("subject_answer5 in", values, "subjectAnswer5");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5NotIn(List<String> values) {
            addCriterion("subject_answer5 not in", values, "subjectAnswer5");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5Between(String value1, String value2) {
            addCriterion("subject_answer5 between", value1, value2, "subjectAnswer5");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswer5NotBetween(String value1, String value2) {
            addCriterion("subject_answer5 not between", value1, value2, "subjectAnswer5");
            return (Criteria) this;
        }

        public Criteria andPapeStateIsNull() {
            addCriterion("pape_state is null");
            return (Criteria) this;
        }

        public Criteria andPapeStateIsNotNull() {
            addCriterion("pape_state is not null");
            return (Criteria) this;
        }

        public Criteria andPapeStateEqualTo(Integer value) {
            addCriterion("pape_state =", value, "papeState");
            return (Criteria) this;
        }

        public Criteria andPapeStateNotEqualTo(Integer value) {
            addCriterion("pape_state <>", value, "papeState");
            return (Criteria) this;
        }

        public Criteria andPapeStateGreaterThan(Integer value) {
            addCriterion("pape_state >", value, "papeState");
            return (Criteria) this;
        }

        public Criteria andPapeStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("pape_state >=", value, "papeState");
            return (Criteria) this;
        }

        public Criteria andPapeStateLessThan(Integer value) {
            addCriterion("pape_state <", value, "papeState");
            return (Criteria) this;
        }

        public Criteria andPapeStateLessThanOrEqualTo(Integer value) {
            addCriterion("pape_state <=", value, "papeState");
            return (Criteria) this;
        }

        public Criteria andPapeStateIn(List<Integer> values) {
            addCriterion("pape_state in", values, "papeState");
            return (Criteria) this;
        }

        public Criteria andPapeStateNotIn(List<Integer> values) {
            addCriterion("pape_state not in", values, "papeState");
            return (Criteria) this;
        }

        public Criteria andPapeStateBetween(Integer value1, Integer value2) {
            addCriterion("pape_state between", value1, value2, "papeState");
            return (Criteria) this;
        }

        public Criteria andPapeStateNotBetween(Integer value1, Integer value2) {
            addCriterion("pape_state not between", value1, value2, "papeState");
            return (Criteria) this;
        }

        public Criteria andTotalScoreIsNull() {
            addCriterion("total_score is null");
            return (Criteria) this;
        }

        public Criteria andTotalScoreIsNotNull() {
            addCriterion("total_score is not null");
            return (Criteria) this;
        }

        public Criteria andTotalScoreEqualTo(Integer value) {
            addCriterion("total_score =", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreNotEqualTo(Integer value) {
            addCriterion("total_score <>", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreGreaterThan(Integer value) {
            addCriterion("total_score >", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_score >=", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreLessThan(Integer value) {
            addCriterion("total_score <", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreLessThanOrEqualTo(Integer value) {
            addCriterion("total_score <=", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreIn(List<Integer> values) {
            addCriterion("total_score in", values, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreNotIn(List<Integer> values) {
            addCriterion("total_score not in", values, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreBetween(Integer value1, Integer value2) {
            addCriterion("total_score between", value1, value2, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("total_score not between", value1, value2, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTestTimeIsNull() {
            addCriterion("test_time is null");
            return (Criteria) this;
        }

        public Criteria andTestTimeIsNotNull() {
            addCriterion("test_time is not null");
            return (Criteria) this;
        }

        public Criteria andTestTimeEqualTo(Date value) {
            addCriterion("test_time =", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeNotEqualTo(Date value) {
            addCriterion("test_time <>", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeGreaterThan(Date value) {
            addCriterion("test_time >", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("test_time >=", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeLessThan(Date value) {
            addCriterion("test_time <", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeLessThanOrEqualTo(Date value) {
            addCriterion("test_time <=", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeIn(List<Date> values) {
            addCriterion("test_time in", values, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeNotIn(List<Date> values) {
            addCriterion("test_time not in", values, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeBetween(Date value1, Date value2) {
            addCriterion("test_time between", value1, value2, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeNotBetween(Date value1, Date value2) {
            addCriterion("test_time not between", value1, value2, "testTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_paper
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_paper
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}