package com.roy.model;

public class Select {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_select.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_select.selection_id
     *
     * @mbg.generated
     */
    private String selectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_select.teac_course_id
     *
     * @mbg.generated
     */
    private Long teacCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_select.exam_id
     *
     * @mbg.generated
     */
    private Integer examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_select.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_select.dificult
     *
     * @mbg.generated
     */
    private String dificult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_select.type1
     *
     * @mbg.generated
     */
    private String type1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_select.type2
     *
     * @mbg.generated
     */
    private String type2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_select.type3
     *
     * @mbg.generated
     */
    private String type3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_select.type4
     *
     * @mbg.generated
     */
    private String type4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_select.answer
     *
     * @mbg.generated
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_select.id
     *
     * @return the value of t_select.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_select.id
     *
     * @param id the value for t_select.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_select.selection_id
     *
     * @return the value of t_select.selection_id
     *
     * @mbg.generated
     */
    public String getSelectionId() {
        return selectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_select.selection_id
     *
     * @param selectionId the value for t_select.selection_id
     *
     * @mbg.generated
     */
    public void setSelectionId(String selectionId) {
        this.selectionId = selectionId == null ? null : selectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_select.teac_course_id
     *
     * @return the value of t_select.teac_course_id
     *
     * @mbg.generated
     */
    public Long getTeacCourseId() {
        return teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_select.teac_course_id
     *
     * @param teacCourseId the value for t_select.teac_course_id
     *
     * @mbg.generated
     */
    public void setTeacCourseId(Long teacCourseId) {
        this.teacCourseId = teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_select.exam_id
     *
     * @return the value of t_select.exam_id
     *
     * @mbg.generated
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_select.exam_id
     *
     * @param examId the value for t_select.exam_id
     *
     * @mbg.generated
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_select.title
     *
     * @return the value of t_select.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_select.title
     *
     * @param title the value for t_select.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_select.dificult
     *
     * @return the value of t_select.dificult
     *
     * @mbg.generated
     */
    public String getDificult() {
        return dificult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_select.dificult
     *
     * @param dificult the value for t_select.dificult
     *
     * @mbg.generated
     */
    public void setDificult(String dificult) {
        this.dificult = dificult == null ? null : dificult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_select.type1
     *
     * @return the value of t_select.type1
     *
     * @mbg.generated
     */
    public String getType1() {
        return type1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_select.type1
     *
     * @param type1 the value for t_select.type1
     *
     * @mbg.generated
     */
    public void setType1(String type1) {
        this.type1 = type1 == null ? null : type1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_select.type2
     *
     * @return the value of t_select.type2
     *
     * @mbg.generated
     */
    public String getType2() {
        return type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_select.type2
     *
     * @param type2 the value for t_select.type2
     *
     * @mbg.generated
     */
    public void setType2(String type2) {
        this.type2 = type2 == null ? null : type2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_select.type3
     *
     * @return the value of t_select.type3
     *
     * @mbg.generated
     */
    public String getType3() {
        return type3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_select.type3
     *
     * @param type3 the value for t_select.type3
     *
     * @mbg.generated
     */
    public void setType3(String type3) {
        this.type3 = type3 == null ? null : type3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_select.type4
     *
     * @return the value of t_select.type4
     *
     * @mbg.generated
     */
    public String getType4() {
        return type4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_select.type4
     *
     * @param type4 the value for t_select.type4
     *
     * @mbg.generated
     */
    public void setType4(String type4) {
        this.type4 = type4 == null ? null : type4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_select.answer
     *
     * @return the value of t_select.answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_select.answer
     *
     * @param answer the value for t_select.answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}