package com.roy.model;

public class StuCourse {


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_course.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_course.stu_id
     *
     * @mbg.generated
     */
    private Long stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_course.teac_course_id
     *
     * @mbg.generated
     */
    private Long teacCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_course.course_type
     *
     * @mbg.generated
     */
    private String courseType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_course.id
     *
     * @return the value of t_stu_course.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_course.id
     *
     * @param id the value for t_stu_course.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_course.stu_id
     *
     * @return the value of t_stu_course.stu_id
     *
     * @mbg.generated
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_course.stu_id
     *
     * @param stuId the value for t_stu_course.stu_id
     *
     * @mbg.generated
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_course.teac_course_id
     *
     * @return the value of t_stu_course.teac_course_id
     *
     * @mbg.generated
     */
    public Long getTeacCourseId() {
        return teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_course.teac_course_id
     *
     * @param teacCourseId the value for t_stu_course.teac_course_id
     *
     * @mbg.generated
     */
    public void setTeacCourseId(Long teacCourseId) {
        this.teacCourseId = teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_course.course_type
     *
     * @return the value of t_stu_course.course_type
     *
     * @mbg.generated
     */
    public String getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_course.course_type
     *
     * @param courseType the value for t_stu_course.course_type
     *
     * @mbg.generated
     */
    public void setCourseType(String courseType) {
        this.courseType = courseType == null ? null : courseType.trim();
    }

    public StuCourse() {
    }

    public StuCourse(Long id, Long stuId, Long teacCourseId, String courseType) {
        this.id = id;
        this.stuId = stuId;
        this.teacCourseId = teacCourseId;
        this.courseType = courseType;
    }
}