package com.roy.model;

public class Student {

    //旧密码
    private String oldPwd;

    public String getOldPwd() {
        return oldPwd;
    }

    public void setOldPwd(String oldPwd) {
        this.oldPwd = oldPwd;
    }


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_name
     *
     * @mbg.generated
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_num
     *
     * @mbg.generated
     */
    private String stuNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_grade
     *
     * @mbg.generated
     */
    private String stuGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_gender
     *
     * @mbg.generated
     */
    private String stuGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_address
     *
     * @mbg.generated
     */
    private String stuAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_class
     *
     * @mbg.generated
     */
    private String stuClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_password
     *
     * @mbg.generated
     */
    private String stuPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_question
     *
     * @mbg.generated
     */
    private String stuQuestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_key
     *
     * @mbg.generated
     */
    private String stuKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_state
     *
     * @mbg.generated
     */
    private Integer stuState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_phone
     *
     * @mbg.generated
     */
    private String stuPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id
     *
     * @return the value of t_student.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id
     *
     * @param id the value for t_student.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_name
     *
     * @return the value of t_student.stu_name
     *
     * @mbg.generated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_name
     *
     * @param stuName the value for t_student.stu_name
     *
     * @mbg.generated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_num
     *
     * @return the value of t_student.stu_num
     *
     * @mbg.generated
     */
    public String getStuNum() {
        return stuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_num
     *
     * @param stuNum the value for t_student.stu_num
     *
     * @mbg.generated
     */
    public void setStuNum(String stuNum) {
        this.stuNum = stuNum == null ? null : stuNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_grade
     *
     * @return the value of t_student.stu_grade
     *
     * @mbg.generated
     */
    public String getStuGrade() {
        return stuGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_grade
     *
     * @param stuGrade the value for t_student.stu_grade
     *
     * @mbg.generated
     */
    public void setStuGrade(String stuGrade) {
        this.stuGrade = stuGrade == null ? null : stuGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_gender
     *
     * @return the value of t_student.stu_gender
     *
     * @mbg.generated
     */
    public String getStuGender() {
        return stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_gender
     *
     * @param stuGender the value for t_student.stu_gender
     *
     * @mbg.generated
     */
    public void setStuGender(String stuGender) {
        this.stuGender = stuGender == null ? null : stuGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_address
     *
     * @return the value of t_student.stu_address
     *
     * @mbg.generated
     */
    public String getStuAddress() {
        return stuAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_address
     *
     * @param stuAddress the value for t_student.stu_address
     *
     * @mbg.generated
     */
    public void setStuAddress(String stuAddress) {
        this.stuAddress = stuAddress == null ? null : stuAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_class
     *
     * @return the value of t_student.stu_class
     *
     * @mbg.generated
     */
    public String getStuClass() {
        return stuClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_class
     *
     * @param stuClass the value for t_student.stu_class
     *
     * @mbg.generated
     */
    public void setStuClass(String stuClass) {
        this.stuClass = stuClass == null ? null : stuClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_password
     *
     * @return the value of t_student.stu_password
     *
     * @mbg.generated
     */
    public String getStuPassword() {
        return stuPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_password
     *
     * @param stuPassword the value for t_student.stu_password
     *
     * @mbg.generated
     */
    public void setStuPassword(String stuPassword) {
        this.stuPassword = stuPassword == null ? null : stuPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_question
     *
     * @return the value of t_student.stu_question
     *
     * @mbg.generated
     */
    public String getStuQuestion() {
        return stuQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_question
     *
     * @param stuQuestion the value for t_student.stu_question
     *
     * @mbg.generated
     */
    public void setStuQuestion(String stuQuestion) {
        this.stuQuestion = stuQuestion == null ? null : stuQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_key
     *
     * @return the value of t_student.stu_key
     *
     * @mbg.generated
     */
    public String getStuKey() {
        return stuKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_key
     *
     * @param stuKey the value for t_student.stu_key
     *
     * @mbg.generated
     */
    public void setStuKey(String stuKey) {
        this.stuKey = stuKey == null ? null : stuKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_state
     *
     * @return the value of t_student.stu_state
     *
     * @mbg.generated
     */
    public Integer getStuState() {
        return stuState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_state
     *
     * @param stuState the value for t_student.stu_state
     *
     * @mbg.generated
     */
    public void setStuState(Integer stuState) {
        this.stuState = stuState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_phone
     *
     * @return the value of t_student.stu_phone
     *
     * @mbg.generated
     */
    public String getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_phone
     *
     * @param stuPhone the value for t_student.stu_phone
     *
     * @mbg.generated
     */
    public void setStuPhone(String stuPhone) {
        this.stuPhone = stuPhone == null ? null : stuPhone.trim();
    }

    public Student() {
    }

    public Student(String oldPwd, Long id, String stuName, String stuNum, String stuGrade,
                   String stuGender, String stuAddress, String stuClass, String stuPassword,
                   String stuQuestion, String stuKey, Integer stuState, String stuPhone) {
        this.oldPwd = oldPwd;
        this.id = id;
        this.stuName = stuName;
        this.stuNum = stuNum;
        this.stuGrade = stuGrade;
        this.stuGender = stuGender;
        this.stuAddress = stuAddress;
        this.stuClass = stuClass;
        this.stuPassword = stuPassword;
        this.stuQuestion = stuQuestion;
        this.stuKey = stuKey;
        this.stuState = stuState;
        this.stuPhone = stuPhone;
    }

    @Override
    public String toString() {
        return "Student{" +
                "oldPwd='" + oldPwd + '\'' +
                ", id=" + id +
                ", stuName='" + stuName + '\'' +
                ", stuNum='" + stuNum + '\'' +
                ", stuGrade='" + stuGrade + '\'' +
                ", stuGender='" + stuGender + '\'' +
                ", stuAddress='" + stuAddress + '\'' +
                ", stuClass='" + stuClass + '\'' +
                ", stuPassword='" + stuPassword + '\'' +
                ", stuQuestion='" + stuQuestion + '\'' +
                ", stuKey='" + stuKey + '\'' +
                ", stuState=" + stuState +
                ", stuPhone='" + stuPhone + '\'' +
                '}';
    }
}