package com.roy.model;

public class StuScore {

    private String courseName;

    private  String stuName;

    private  String teacName;

    private Integer paperState;

    public Integer getPaperState() {
        return paperState;
    }

    public void setPaperState(Integer paperState) {
        this.paperState = paperState;
    }

    public String getTeacName() {
        return teacName;
    }

    public void setTeacName(String teacName) {
        this.teacName = teacName;
    }

    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public String getStuName() {
        return stuName;
    }

    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_score.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_score.paper_id
     *
     * @mbg.generated
     */
    private Long paperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_score.stu_id
     *
     * @mbg.generated
     */
    private Long stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_score.teac_course_id
     *
     * @mbg.generated
     */
    private Long teacCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_score.selection_count
     *
     * @mbg.generated
     */
    private Integer selectionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_score.multi_selection_count
     *
     * @mbg.generated
     */
    private Integer multiSelectionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_score.judge_count
     *
     * @mbg.generated
     */
    private Integer judgeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_score.fill_count
     *
     * @mbg.generated
     */
    private Integer fillCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_score.subject_count
     *
     * @mbg.generated
     */
    private Integer subjectCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_score.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_score.test_time
     *
     * @mbg.generated
     */
    private Integer testTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_score.calculate_count
     *
     * @mbg.generated
     */
    private Integer calculateCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_score.id
     *
     * @return the value of t_stu_score.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_score.id
     *
     * @param id the value for t_stu_score.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_score.paper_id
     *
     * @return the value of t_stu_score.paper_id
     *
     * @mbg.generated
     */
    public Long getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_score.paper_id
     *
     * @param paperId the value for t_stu_score.paper_id
     *
     * @mbg.generated
     */
    public void setPaperId(Long paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_score.stu_id
     *
     * @return the value of t_stu_score.stu_id
     *
     * @mbg.generated
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_score.stu_id
     *
     * @param stuId the value for t_stu_score.stu_id
     *
     * @mbg.generated
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_score.teac_course_id
     *
     * @return the value of t_stu_score.teac_course_id
     *
     * @mbg.generated
     */
    public Long getTeacCourseId() {
        return teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_score.teac_course_id
     *
     * @param teacCourseId the value for t_stu_score.teac_course_id
     *
     * @mbg.generated
     */
    public void setTeacCourseId(Long teacCourseId) {
        this.teacCourseId = teacCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_score.selection_count
     *
     * @return the value of t_stu_score.selection_count
     *
     * @mbg.generated
     */
    public Integer getSelectionCount() {
        return selectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_score.selection_count
     *
     * @param selectionCount the value for t_stu_score.selection_count
     *
     * @mbg.generated
     */
    public void setSelectionCount(Integer selectionCount) {
        this.selectionCount = selectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_score.multi_selection_count
     *
     * @return the value of t_stu_score.multi_selection_count
     *
     * @mbg.generated
     */
    public Integer getMultiSelectionCount() {
        return multiSelectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_score.multi_selection_count
     *
     * @param multiSelectionCount the value for t_stu_score.multi_selection_count
     *
     * @mbg.generated
     */
    public void setMultiSelectionCount(Integer multiSelectionCount) {
        this.multiSelectionCount = multiSelectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_score.judge_count
     *
     * @return the value of t_stu_score.judge_count
     *
     * @mbg.generated
     */
    public Integer getJudgeCount() {
        return judgeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_score.judge_count
     *
     * @param judgeCount the value for t_stu_score.judge_count
     *
     * @mbg.generated
     */
    public void setJudgeCount(Integer judgeCount) {
        this.judgeCount = judgeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_score.fill_count
     *
     * @return the value of t_stu_score.fill_count
     *
     * @mbg.generated
     */
    public Integer getFillCount() {
        return fillCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_score.fill_count
     *
     * @param fillCount the value for t_stu_score.fill_count
     *
     * @mbg.generated
     */
    public void setFillCount(Integer fillCount) {
        this.fillCount = fillCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_score.subject_count
     *
     * @return the value of t_stu_score.subject_count
     *
     * @mbg.generated
     */
    public Integer getSubjectCount() {
        return subjectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_score.subject_count
     *
     * @param subjectCount the value for t_stu_score.subject_count
     *
     * @mbg.generated
     */
    public void setSubjectCount(Integer subjectCount) {
        this.subjectCount = subjectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_score.score
     *
     * @return the value of t_stu_score.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_score.score
     *
     * @param score the value for t_stu_score.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_score.test_time
     *
     * @return the value of t_stu_score.test_time
     *
     * @mbg.generated
     */
    public Integer getTestTime() {
        return testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_score.test_time
     *
     * @param testTime the value for t_stu_score.test_time
     *
     * @mbg.generated
     */
    public void setTestTime(Integer testTime) {
        this.testTime = testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_score.calculate_count
     *
     * @return the value of t_stu_score.calculate_count
     *
     * @mbg.generated
     */
    public Integer getCalculateCount() {
        return calculateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_score.calculate_count
     *
     * @param calculateCount the value for t_stu_score.calculate_count
     *
     * @mbg.generated
     */
    public void setCalculateCount(Integer calculateCount) {
        this.calculateCount = calculateCount;
    }

    public StuScore() {
    }

    public StuScore(String courseName, String stuName, String teacName, Long id,
                    Long paperId, Long stuId, Long teacCourseId, Integer selectionCount,
                    Integer multiSelectionCount, Integer judgeCount, Integer fillCount,
                    Integer subjectCount, Integer score, Integer testTime, Integer calculateCount) {
        this.courseName = courseName;
        this.stuName = stuName;
        this.teacName = teacName;
        this.id = id;
        this.paperId = paperId;
        this.stuId = stuId;
        this.teacCourseId = teacCourseId;
        this.selectionCount = selectionCount;
        this.multiSelectionCount = multiSelectionCount;
        this.judgeCount = judgeCount;
        this.fillCount = fillCount;
        this.subjectCount = subjectCount;
        this.score = score;
        this.testTime = testTime;
        this.calculateCount = calculateCount;
    }

    @Override
    public String toString() {
        return "StuScore{" +
                "courseName='" + courseName + '\'' +
                ", stuName='" + stuName + '\'' +
                ", teacName='" + teacName + '\'' +
                ", id=" + id +
                ", paperId=" + paperId +
                ", stuId=" + stuId +
                ", teacCourseId=" + teacCourseId +
                ", selectionCount=" + selectionCount +
                ", multiSelectionCount=" + multiSelectionCount +
                ", judgeCount=" + judgeCount +
                ", fillCount=" + fillCount +
                ", subjectCount=" + subjectCount +
                ", score=" + score +
                ", testTime=" + testTime +
                ", calculateCount=" + calculateCount +
                '}';
    }
}