package com.roy.model;

import org.apache.ibatis.annotations.Param;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;

public class TeacCourse {


    private String courseName;
    private BigDecimal courseCredit;
    private String teacName;
    private Long stuId;
    private String courseType;
    private String courseNum;
    private String title;
    private String dificult;
    private String questionType;

    public String getQuestionType() {
        return questionType;
    }

    public void setQuestionType(String questionType) {
        this.questionType = questionType;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDificult() {
        return dificult;
    }

    public void setDificult(String dificult) {
        this.dificult = dificult;
    }

    public String getCourseNum() {
        return courseNum;
    }

    public void setCourseNum(String courseNum) {
        this.courseNum = courseNum;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teac_course.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teac_course.teac_id
     *
     * @mbg.generated
     */
    private Long teacId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teac_course.course_id
     *
     * @mbg.generated
     */
    private Long courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teac_course.start_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teac_course.end_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teac_course.id
     *
     * @return the value of t_teac_course.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teac_course.id
     *
     * @param id the value for t_teac_course.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teac_course.teac_id
     *
     * @return the value of t_teac_course.teac_id
     *
     * @mbg.generated
     */
    public Long getTeacId() {
        return teacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teac_course.teac_id
     *
     * @param teacId the value for t_teac_course.teac_id
     *
     * @mbg.generated
     */
    public void setTeacId(Long teacId) {
        this.teacId = teacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teac_course.course_id
     *
     * @return the value of t_teac_course.course_id
     *
     * @mbg.generated
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teac_course.course_id
     *
     * @param courseId the value for t_teac_course.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teac_course.start_time
     *
     * @return the value of t_teac_course.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teac_course.start_time
     *
     * @param startTime the value for t_teac_course.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teac_course.end_time
     *
     * @return the value of t_teac_course.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teac_course.end_time
     *
     * @param endTime the value for t_teac_course.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }


    public Long getStuId() {
        return stuId;
    }

    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }



    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public BigDecimal getCourseCredit() {
        return courseCredit;
    }

    public void setCourseCredit(BigDecimal courseCredit) {
        this.courseCredit = courseCredit;
    }

    public String getTeacName() {
        return teacName;
    }

    public void setTeacName(String teacName) {
        this.teacName = teacName;
    }



    public String getCourseType() {
        return courseType;
    }

    public void setCourseType(String courseType) {
        this.courseType = courseType;
    }
    public TeacCourse() {
    }
    public TeacCourse(Long id, Long teacId, Long courseId, Date startTime,
                      Date endTime) {
        this.id = id;
        this.teacId = teacId;
        this.courseId = courseId;
        this.startTime = startTime;
        this.endTime = endTime;
    }
    public TeacCourse(String courseName, BigDecimal courseCredit,
                      String teacName, Long stuId, String courseType,
                      Long id, Long teacId, Long courseId, Date startTime,
                      Date endTime) {
        this.courseName = courseName;
        this.courseCredit = courseCredit;
        this.teacName = teacName;
        this.stuId = stuId;
        this.courseType = courseType;
        this.id = id;
        this.teacId = teacId;
        this.courseId = courseId;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    @Override
    public String toString() {
        return "TeacCourse{" +
                "courseName='" + courseName + '\'' +
                ", courseCredit=" + courseCredit +
                ", teacName='" + teacName + '\'' +
                ", stuId=" + stuId +
                ", courseType='" + courseType + '\'' +
                ", id=" + id +
                ", teacId=" + teacId +
                ", courseId=" + courseId +
                ", startTime=" + startTime +
                ", endTime=" + endTime +
                '}';
    }
}